### ISSUE TITLE
Fails to build with -Werror=format-overflow set

### ISSUE THREAD

**Issue by Sesivany** [majn/tgl#19] opened 2017-06-26 16:14 UTC
Fedora now builds with -Werror=format-overflow option on and tgl and thus telegram-purple fails to build on 32-bit architectures (i686 and armv7l).

You can see the build log here for details:
https://kojipkgs.fedoraproject.org//work/tasks/6399/20186399/build.log

**Comment by BenWiederhake** [comment] 2017-06-26 19:21
1) Why is the build environment `root/root`?  That potentially hides a lot of bugs.
2) Hmm, I could have sworn I already saw this as a bug report not too long ago.  I'll look into it.  I think it was due to the compiler also accounting for the sign, even though the result can easily be proven (by a human) to be nonnegative, per spec of `lrand48`.

**Comment by BenWiederhake** [comment] 2017-06-26 20:17
There you go.  Please wait with closing until 1.4.0 ships, which is going to take a looong time.

**Comment by BenWiederhake** [comment] 2017-06-26 20:18
Can you please verify that it works?  I can't reproduce the original error easily.

**Closed** 2019-02-22 21:39 UTC
Labels: in-pipeline
